spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/cloudBalance
    username: root
    password: Mohit@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG

# change swagger-ui path (optional)
springdoc:
  swagger-ui:
    path: /swagger-ui.html

  # change base api docs path (optional)
  api-docs:
    path: /v3/api-docs

#You can view ALL active auto-configs
#debug: true

jwt:
  secretKey: avjfahsiuv90g0248q84h39nv3rejfqj09waeur09q348fq93hrfqaijdps09qu9408qv3naeoufvjsfj0q843h9hre9afspijarwe

